# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pib',
            name='phone_number',
            field=models.CharField(default='+', max_length=12, unique=True),
        ),
    ]
