# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_pib_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pib',
            options={'verbose_name': 'Користувач', 'verbose_name_plural': 'Користувачі'},
        ),
        migrations.AddField(
            model_name='pib',
            name='email',
            field=models.EmailField(default='example@email.com', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='pib',
            name='phone_number',
            field=models.CharField(default='+380', max_length=12, unique=True, verbose_name='номер телефону'),
        ),
    ]
