# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-14 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20170629_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pib',
            name='email',
            field=models.EmailField(default='example@email.co', max_length=254, verbose_name='E-mail'),
        ),
    ]
