# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20170814_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'Товар в замовленні', 'verbose_name_plural': 'Товарыв замовленні'},
        ),
    ]
