# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
    ]
